apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back-container
        image: 752518105514.dkr.ecr.ap-northeast-2.amazonaws.com/kakaoasset-backend:527350b69735837c41d5613db61572779ea334a1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: back-cm
        - configMapRef:
            name: elasticsearch-cm
        - secretRef:
            name: back-sec
        resources:
          requests:
            memory: "500Mi"
            cpu: 1500m
          limits:
            memory: "1000Mi"
            cpu: 2000m
