apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        image: 752518105514.dkr.ecr.ap-northeast-2.amazonaws.com/kakaoasset-backend:b7dc317422ba24c4c9ae08c9c7bdf36290ae02a9
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: back-cm
        - configMapRef:
            name: elasticsearch-cm
        - secretRef:
            name: back-sec
        resources:
          requests:
            memory: "500Mi"
            cpu: 1500m
          limits:
            memory: "1000Mi"
            cpu: 2000m
