apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: 752518105514.dkr.ecr.ap-northeast-2.amazonaws.com/kakaoasset-frontend:f66cd3a5dc932fb0ec156ed663bff603d3e402f1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: front-cm
        - configMapRef:
            name: elasticsearch-cm
        resources:
          requests:
            memory: "1000Mi"
            cpu: 1500m
          limits:
            memory: "2000Mi"
            cpu: 2000m
