apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: ehdwn15100/frontend:1.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: front-cm
        resources:
          requests:
            memory: "1000Mi"
            cpu: 1500m
          limits:
            memory: "2000Mi"
            cpu: 2000m
