apiVersion: v1
data:
  REACT_APP_BACKEND_URI: http://back:8080/
  REACT_APP_KAKAO_CLIENT_ID: 12826fef7f7511bec960427871f356f1
  REACT_APP_KAKAO_REDIRECT_URI: http://k8s-release-ingressf-86e49014a3-453848130.ap-northeast-2.elb.amazonaws.com/oauth/kakao
kind: ConfigMap
metadata:
  name: front-cm
