apiVersion: batch/v1
kind: CronJob
metadata:
  name: indexclear-cj
spec:
  # “At 00:00 on every day-of-month if it's on every day-of-week from Monday through Friday.”
  # schedule: "CRON_TZ=Asia/Seoul 0 0 */1 * 1-5"
  schedule: "CRON_TZ=Asia/Seoul */5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: indexclear-cj
            image: zxcasd3004/kakaoasset:indexclear
            envFrom:
            - configMapRef:
                name: elasticsearch-cm
          restartPolicy: Never
