apiVersion: batch/v1
kind: CronJob
metadata:
  name: multistock-cj
spec:
  # “At every minute past every hour from 9 through 16 on every day-of-week from Monday through Friday.”
  # schedule: "CRON_TZ=Asia/Seoul */1 9-16 * * 1-5"
  schedule: "CRON_TZ=Asia/Seoul */1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: multistock-cj
            image: zxcasd3004/kakaoasset:multistock
            envFrom:
            - configMapRef:
                name: elasticsearch-cm
          restartPolicy: Never
