apiVersion: batch/v1
kind: CronJob
metadata:
  name: stocklist-cj
spec:
  # “At 08:56 on every day-of-month if it's on every day-of-week from Monday through Friday.”
  schedule: "CRON_TZ=Asia/Seoul 56 8 */1 * 1-5"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stocklist-cj
            image: zxcasd3004/kakaoasset:stocklist
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: elasticsearch-cm
          restartPolicy: Never
