apiVersion: batch/v1
kind: CronJob
metadata:
  name: trend-cj
spec:
  # “At 23:50 on every day-of-month.”
  schedule: "CRON_TZ=Asia/Seoul 50 23 */1 * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trend-cj
            image: zxcasd3004/kakaoasset:trend
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: db-sec
          restartPolicy: Never
